export type {
  CrmPhone,
  CrmEmail,
  CrmActivityType,
  CrmActivity,
  CrmAttachment,
  CrmPerson,
  CrmCompany,
  CrmRfqDiscipline,
  CrmRfqStage,
  CrmEnquiryCore,
  CrmRfq,
  CrmQuoteStatus,
  CrmLostReason,
  CrmQuote,
  CrmProject,
} from '../../../shared/models/ICrm';
